In [3]:
import numpy as np
#array - collection of same data type
calls  = np.array([5,7,8,9,11])
print (calls)

[ 5  7  8  9 11]


In [15]:
#pip install packages = 'pip install pakages'
import numpy as np
calls = np.array([['jan','feb','mar'],[300,400,500]])
print (calls)

[['jan' 'feb' 'mar']
 ['300' '400' '500']]


In [16]:
import numpy as np
calls = np.array([['jan','feb','mar'],[300,400,500]])
calls[1]


array(['300', '400', '500'], dtype='<U21')

In [14]:
import numpy as np
calls = np.array([['jan','feb','mar'],[300,400,500]])
calls[1,:]

array(['300', '400', '500'], dtype='<U21')

In [19]:
import numpy as np
calls = np.array([['jan','feb','mar'],[300,400,500]])
calls[0,:]

array(['jan', 'feb', 'mar'], dtype='<U21')

In [9]:
calls.shape

(2, 3)

In [21]:
monthlycalls = np.array([['Jan','Mar','feb'],
                         [2,2,7],
                         [5,6,5],
                         [3,8,4]])
monthlycalls[1,2]


np.str_('7')

In [23]:
monthlycalls = np.array([['Jan','Mar','feb'],
                         [2,2,7],
                         [5,6,5],
                         [3,8,4]])
monthlycalls[1]

array(['2', '2', '7'], dtype='<U21')

In [27]:
import numpy as np
numbers = np.array([3,6,4,2,3,1])
numbers = [numbers>3]
print(numbers)

[array([False,  True,  True, False, False, False])]


In [32]:
import numpy as np
numbers = np.array([3,6,4,2,3,1,7,9])
numbers = [2&4]
print(numbers)

[0]


In [35]:
import numpy as np
numbers = np.array([3,6,4,2,3,1,7,9])
filtered_numbers = numbers[(numbers>=2) & (numbers <=9)]
print(filtered_numbers)

[3 6 4 2 3 7 9]


In [36]:
import numpy as np
numbers = np.array([3,6,4,2,3,1,7,9])
np.sum(numbers)

np.int64(35)

In [38]:
import numpy as np
numbers = np.array([3,6,4,2,3,1,7,9])
np.max(numbers)

np.int64(9)

In [39]:
import numpy as np
numbers = np.array([3,6,4,2,3,1,7,9])
np.min(numbers)

np.int64(1)

In [40]:
import numpy as np
numbers = np.array([3,6,4,2,3,1,7,9])
np.mean(numbers)

np.float64(4.375)

In [41]:
import numpy as np
numbers = np.array([3,6,4,2,3,1,7,9])
np.std(numbers)

np.float64(2.54644359843292)

In [42]:
#2 dimensional array
monthlycalls = np.array([[5,6,5],
                         [3,8,4]])
total_calls = np.sum(monthlycalls)
print('number_of_calls',total_calls)

number_of_calls 31


In [43]:
monthlycalls = np.array([['Jan','Mar','feb'],
                         [2,2,7],
                         [5,6,5],
                         [3,8,4]])
np.sum(monthlycalls[1:].astype(int))

np.int64(42)

In [45]:
North = np.array([5,100,30])
South = np.array([3,2,5])
np.concatenate((North,South))

array([  5, 100,  30,   3,   2,   5])

In [46]:
North = np.array([5,100,30])
South = np.array([3,2,5])
np.add(North,South)

array([  8, 102,  35])

In [48]:
month_total = np.array([['Jan','Feb','Mar'],
                        [200,30,400],
                        [30,50,80]])
column_totals=np.sum(month_total[1:].astype(int),axis=0)
print(column_totals)


[230  80 480]


In [49]:
rows=np.array([40,80,50,20,30])
result = np.split(rows,[2,4])
print(result)


[array([40, 80]), array([50, 20]), array([30])]
